apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-application
  labels:
    app:  ecom-application
  namespace: default
spec:
  selector:
    matchLabels:
      app:  ecom-application
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app:  ecom-application
    spec:
      containers:
      - name:  ecom-application
        image: sanjai1603/test-flux:v3
        ports:
        - containerPort: 5173
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name:  ecom-application
