apiVersion: v1
kind: Service
metadata:
  namespace: default
  name:  ecom-application
  labels:
    app:  ecom-application
spec:
  type: ClusterIP
  selector:
    app:  ecom-application
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5173
